[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$P1w8OhMS$x0g14j.A/DJ2y4NE1TOkr/"
  ]

[http.routers.api]
  rule = "Host(`monitor.your_domain`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"